"""Seed definitions for phase-1 capabilities."""

from __future__ import annotations

from typing import Any

CAPABILITIES: list[dict[str, Any]] = [
    {
        "id": "list_capabilities",
        "name": "List Capabilities",
        "description": "List active system capabilities",
        "category": "system",
        "input_schema": {"type": "object", "properties": {}},
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "list_capabilities",
    },
    {
        "id": "get_market_snapshot",
        "name": "Get Market Snapshot",
        "description": "Fetch ETF/index snapshot quotes via market-data (a-stock-data)",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {"codes": {"type": "array", "items": {"type": "string"}}},
            "required": ["codes"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_market_snapshot",
    },
    {
        "id": "get_etf_history",
        "name": "Get ETF History",
        "description": "Fetch ETF OHLCV history",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {
                "code": {"type": "string"},
                "count": {"type": "integer", "default": 60},
                "period": {"type": "string", "default": "day"},
                "adjust": {"type": "string", "default": "qfq"},
            },
            "required": ["code"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_etf_history",
    },
    {
        "id": "get_trading_calendar",
        "name": "Get Trading Calendar",
        "description": "Official-ish trading calendar for a month",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {
                "year": {"type": "integer"},
                "month": {"type": "integer"},
            },
            "required": ["year", "month"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_trading_calendar",
    },
    {
        "id": "submit_observation",
        "name": "Submit Observation",
        "description": "Record a market observation",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {"type": "string"},
                "data": {"type": "object"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_observation",
    },
    {
        "id": "submit_thesis",
        "name": "Submit Thesis",
        "description": "Record an investment thesis",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {"type": "string"},
                "observation_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_thesis",
    },
    {
        "id": "submit_decision",
        "name": "Submit Decision",
        "description": "Record an investment decision linked to observation/thesis",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "summary": {"type": "string"},
                "hypothesis": {"type": "string"},
                "action_plan": {"type": "string"},
                "observation_id": {"type": "integer"},
                "thesis_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["summary"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_decision",
    },
    {
        "id": "submit_order",
        "name": "Submit Order",
        "description": "Paper-trade order (simulated fill)",
        "category": "execution",
        "input_schema": {
            "type": "object",
            "properties": {
                "symbol": {"type": "string"},
                "side": {"type": "string", "enum": ["buy", "sell"]},
                "quantity": {"type": "number"},
                "decision_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["symbol", "side", "quantity"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_order",
    },
    {
        "id": "get_portfolio",
        "name": "Get Portfolio",
        "description": "Cash, positions, and latest snapshot",
        "category": "portfolio",
        "input_schema": {"type": "object", "properties": {}},
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_portfolio",
    },
    {
        "id": "submit_review",
        "name": "Submit Review",
        "description": "Review a decision with mandatory issue classification",
        "category": "review",
        "input_schema": {
            "type": "object",
            "properties": {
                "issue_type": {
                    "type": "string",
                    "enum": [
                        "DecisionError",
                        "DataGap",
                        "CapabilityGap",
                        "ToolUsageError",
                    ],
                },
                "content": {"type": "string"},
                "decision_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
                "create_change_request": {"type": "boolean"},
                "change_request": {"type": "object"},
            },
            "required": ["issue_type", "content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_review",
    },
    {
        "id": "create_change_request",
        "name": "Create Change Request",
        "description": "Propose a system capability/data improvement",
        "category": "evolution",
        "input_schema": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "problem": {"type": "string"},
                "evidence": {"type": "string"},
                "proposal": {"type": "string"},
                "expected_benefit": {"type": "string"},
                "issue_type": {
                    "type": "string",
                    "enum": ["DataGap", "CapabilityGap"],
                },
            },
            "required": ["title", "problem", "issue_type"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "create_change_request",
    },
    {
        "id": "list_change_requests",
        "name": "List Change Requests",
        "description": "List system change requests",
        "category": "evolution",
        "input_schema": {
            "type": "object",
            "properties": {"status": {"type": "string"}},
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "list_change_requests",
    },
    {
        "id": "start_agent_run",
        "name": "Start Agent Run",
        "description": "Open an agent run record",
        "category": "system",
        "input_schema": {
            "type": "object",
            "properties": {"trigger": {"type": "string"}, "notes": {"type": "string"}},
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "start_agent_run",
    },
    {
        "id": "finish_agent_run",
        "name": "Finish Agent Run",
        "description": "Close an agent run record",
        "category": "system",
        "input_schema": {
            "type": "object",
            "properties": {
                "agent_run_id": {"type": "integer"},
                "status": {"type": "string"},
                "notes": {"type": "string"},
            },
            "required": ["agent_run_id"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "finish_agent_run",
    },
]