"""第一期 Capability 种子定义。"""

from __future__ import annotations

from typing import Any

CAPABILITIES: list[dict[str, Any]] = [
    {
        "id": "list_capabilities",
        "name": "列出系统能力",
        "description": "列出当前可用的系统 Capability",
        "category": "system",
        "input_schema": {"type": "object", "properties": {}},
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "list_capabilities",
    },
    {
        "id": "get_market_snapshot",
        "name": "获取行情快照",
        "description": "通过 market-data（a-stock-data）获取 ETF/指数快照报价",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {"codes": {"type": "array", "items": {"type": "string"}}},
            "required": ["codes"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_market_snapshot",
    },
    {
        "id": "get_etf_history",
        "name": "获取 ETF 历史行情",
        "description": "获取 ETF 的 OHLCV 历史 K 线",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {
                "code": {"type": "string"},
                "count": {"type": "integer", "default": 60},
                "period": {"type": "string", "default": "day"},
                "adjust": {"type": "string", "default": "qfq"},
            },
            "required": ["code"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_etf_history",
    },
    {
        "id": "get_trading_calendar",
        "name": "获取交易日历",
        "description": "获取指定年月的交易日历",
        "category": "market",
        "input_schema": {
            "type": "object",
            "properties": {
                "year": {"type": "integer"},
                "month": {"type": "integer"},
            },
            "required": ["year", "month"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_trading_calendar",
    },
    {
        "id": "submit_observation",
        "name": "提交市场观察",
        "description": "记录一条市场观察（请使用中文）",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {"type": "string"},
                "data": {"type": "object"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_observation",
    },
    {
        "id": "submit_thesis",
        "name": "提交投资论点",
        "description": "记录投资论点（请使用中文）",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {"type": "string"},
                "observation_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_thesis",
    },
    {
        "id": "submit_decision",
        "name": "提交投资决策",
        "description": "记录投资决策并关联观察/论点（摘要与假设请使用中文）",
        "category": "decision",
        "input_schema": {
            "type": "object",
            "properties": {
                "summary": {"type": "string"},
                "hypothesis": {"type": "string"},
                "action_plan": {"type": "string"},
                "observation_id": {"type": "integer"},
                "thesis_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["summary"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_decision",
    },
    {
        "id": "submit_order",
        "name": "提交模拟订单",
        "description": "纸面交易下单（模拟成交）",
        "category": "execution",
        "input_schema": {
            "type": "object",
            "properties": {
                "symbol": {"type": "string"},
                "side": {"type": "string", "enum": ["buy", "sell"]},
                "quantity": {"type": "number"},
                "decision_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
            },
            "required": ["symbol", "side", "quantity"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_order",
    },
    {
        "id": "get_portfolio",
        "name": "查询投资组合",
        "description": "查询现金、持仓与最新快照",
        "category": "portfolio",
        "input_schema": {"type": "object", "properties": {}},
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "get_portfolio",
    },
    {
        "id": "submit_review",
        "name": "提交复盘",
        "description": "对决策复盘，必须标注问题类型（复盘正文请使用中文）",
        "category": "review",
        "input_schema": {
            "type": "object",
            "properties": {
                "issue_type": {
                    "type": "string",
                    "enum": [
                        "DecisionError",
                        "DataGap",
                        "CapabilityGap",
                        "ToolUsageError",
                    ],
                },
                "content": {"type": "string"},
                "decision_id": {"type": "integer"},
                "agent_run_id": {"type": "integer"},
                "create_change_request": {"type": "boolean"},
                "change_request": {"type": "object"},
            },
            "required": ["issue_type", "content"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "submit_review",
    },
    {
        "id": "create_change_request",
        "name": "创建变更请求",
        "description": "提出系统能力/数据改进建议（正文请使用中文）",
        "category": "evolution",
        "input_schema": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "problem": {"type": "string"},
                "evidence": {"type": "string"},
                "proposal": {"type": "string"},
                "expected_benefit": {"type": "string"},
                "issue_type": {
                    "type": "string",
                    "enum": ["DataGap", "CapabilityGap"],
                },
            },
            "required": ["title", "problem", "issue_type"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "create_change_request",
    },
    {
        "id": "list_change_requests",
        "name": "列出变更请求",
        "description": "列出系统变更请求",
        "category": "evolution",
        "input_schema": {
            "type": "object",
            "properties": {"status": {"type": "string"}},
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "list_change_requests",
    },
    {
        "id": "start_agent_run",
        "name": "开始 Agent 运行",
        "description": "创建一条 AgentRun 记录",
        "category": "system",
        "input_schema": {
            "type": "object",
            "properties": {"trigger": {"type": "string"}, "notes": {"type": "string"}},
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "start_agent_run",
    },
    {
        "id": "finish_agent_run",
        "name": "结束 Agent 运行",
        "description": "关闭一条 AgentRun 记录",
        "category": "system",
        "input_schema": {
            "type": "object",
            "properties": {
                "agent_run_id": {"type": "integer"},
                "status": {"type": "string"},
                "notes": {"type": "string"},
            },
            "required": ["agent_run_id"],
        },
        "output_schema": {"type": "object"},
        "permission": "agent",
        "implementation": "finish_agent_run",
    },
]
